version: "3"

services:
  backend:
    image: "aliadam7/ecars:v1"
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Set from environment variables or .env file
      POSTGRES_DB: ${POSTGRES_DB}  # The name of the database to create
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
